/*
 * Device Driver
 *
 * Microservice for handling connection with Fog Nodes
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package utils

import (
	"bytes"
	"net/http"
	"os/exec"
	"strings"
)

// Returns current host IP address
func GetHostIP() (string, error) {
	// route | awk '/default/ { print $2 }'

	cmd := exec.Command("ash", "-c", "route | awk '/default/ { print $2 }'")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", err
	}

	ip := strings.TrimSuffix(strings.TrimSpace(string(out)), "\n")

	return ip, nil
}

// Performs a POST request
func DoPost(u string, bodyData *bytes.Buffer) (*http.Response, error) {
	if bodyData != nil {
		return http.Post(u, "application/json", bodyData)
	}

	return http.Post(u, "application/json", nil)
}
