/*
 * Device Driver
 *
 * Microservice for handling connection with Fog Nodes
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// A GioDevice represents a device handled by the system
type GioDevice struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name"`
	Mac  string `json:"mac"`
	Room string `json:"room"`
}

// A Reading is a value produce by a device
type Reading struct {
	ID                string `json:"id,omitempty"`
	Name              string `json:"name"`
	Value             string `json:"value"`
	Unit              string `json:"unit"`
	CreationTimestamp string `json:"creation_timestamp,omitempty"`
}

// A Room is a virtual place that may contains devices
type Room struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// A FogNodeDevice represents a device connected to a Fog Node
type FogNodeDevice struct {
	ID              string              `json:"id"`
	Name            string              `json:"name"`
	Characteristics []BLECharacteristic `json:"characteristics"`
}

type ProcessFunc func(reading *Reading) *Reading

// A BLECharacteristic represents a Bluetooth Low Energy Characteristic
type BLECharacteristic struct {
	UUID    string      `json:"uuid"`
	Name    string      `json:"name"`
	Process ProcessFunc `json:"-"`
}

func (blec BLECharacteristic) String() string {
	return blec.UUID
}

// An ActionData represents data for actions
type ActionData struct {
	Value int `json:"value"`
}
